import json
import os
from sqlalchemy import text
from app.db.connection import get_engine, get_schema_summary
from app.data_upload import registry

PROFILE_REPORT_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))), "data", "profile_report.json")

# Embedding tables (vector columns) aren't meaningful for the SQL generator to
# see - they'd just be noise, or worse, something the LLM tries to query directly.
KNOWN_EMBEDDING_TABLES = {"review_embeddings", "dataset_embeddings"}


def _load_cached_profile() -> dict | None:
    """
    Loads the profiling report generated by scripts/run_profiling.py, if it
    exists. Reading a cached file here instead of profiling live keeps SQL
    generation fast - profiling involves several aggregate queries per
    column, which isn't something you want to redo on every single question.
    """
    if os.path.exists(PROFILE_REPORT_PATH):
        with open(PROFILE_REPORT_PATH, "r") as f:
            return json.load(f)
    return None


def build_schema_context(sample_rows: int = 2, include_profile: bool = True) -> str:
    """
    Produces a compact schema description for the LLM prompt, e.g.:

        Table: product_reviews
        Columns: id (integer), product_name (text), price (numeric), ...
        Sample rows:
          (1, 'Wireless Mouse', 799.00, ...)
          (2, 'Wireless Mouse', 799.00, ...)
        Profile notes: price: range 799.0-3499.0, no nulls; region: 4 distinct values

    Including a couple of sample rows measurably helps the LLM guess correct
    value formats (e.g. date format, whether region is 'West' vs 'west').
    Profile notes (Phase 4) add cheap-but-useful hints: knowing a column has
    only 4 distinct values suggests it's categorical and worth an exact-match
    filter; knowing a numeric column's range helps the LLM avoid nonsensical
    bounds in generated WHERE clauses.

    If a dataset has been uploaded (Phase 6.1), the context is restricted to
    just that table - showing the old seed data alongside a fresh upload
    would just confuse the LLM about which table to actually query.
    """
    schema = get_schema_summary()
    engine = get_engine()
    blocks = []

    profile = _load_cached_profile() if include_profile else None

    active_dataset = registry.get_active_dataset()
    focus_tables = {active_dataset["table"]} if active_dataset else set(schema.keys())

    with engine.connect() as conn:
        for table_name, columns in schema.items():
            if table_name not in focus_tables or table_name in KNOWN_EMBEDDING_TABLES:
                continue

            col_desc = ", ".join(f"{name} ({dtype})" for name, dtype in columns)
            block = f"Table: {table_name}\nColumns: {col_desc}"

            if sample_rows > 0:
                try:
                    rows = conn.execute(
                        text(f'SELECT * FROM "{table_name}" LIMIT :n'),
                        {"n": sample_rows},
                    ).fetchall()
                    if rows:
                        sample_text = "\n".join(f"  {tuple(r)}" for r in rows)
                        block += f"\nSample rows:\n{sample_text}"
                except Exception:
                    # Skip sample rows for tables that error (e.g. vector columns
                    # with no straightforward repr) - schema info alone is still useful.
                    pass

            if profile and table_name in profile:
                notes = _format_profile_notes(profile[table_name].get("columns", {}))
                if notes:
                    block += f"\nProfile notes: {notes}"

            blocks.append(block)

    return "\n\n".join(blocks)


def _format_profile_notes(column_profiles: dict) -> str:
    """Condenses per-column profile stats into a short, prompt-friendly line."""
    notes = []
    for col, prof in column_profiles.items():
        if "stats" not in prof:
            continue
        stats = prof["stats"]
        if "min" in stats and stats.get("min") is not None:
            note = f"{col}: range {stats['min']}-{stats['max']}"
        elif "top_values" in stats and stats["top_values"]:
            values = ", ".join(str(v["value"]) for v in stats["top_values"][:3])
            note = f"{col}: common values include {values}"
        else:
            continue

        if prof.get("null_rate", 0) == 0:
            note += ", no nulls"
        if prof.get("distinct_count") is not None and prof["distinct_count"] <= 20:
            note += f", {prof['distinct_count']} distinct values"

        notes.append(note)

    return "; ".join(notes)
